<?php
//새로운 필드를 구성해 주세요 (단, 아래 내용 반드시 주의!)
//write_change_fields,$write_change_sort_fields배열변수는 반드시 존재해야 하며, 구조도 반드시 지켜주세요.
//"wr_id" => "int(11) NOT NULL" 요소는 절대 제거하거나 수정하지 마세요(반드시 필요한 요소입니다.)
//"wr_num" => "int(11) NOT NULL DEFAULT 0" 요소는 절대 제거하거나 수정하지 마세요(반드시 필요한 요소입니다.)
/*
"type" : 필드의 데이터타입을 포함한 컬럼속성
"name" : 필드의 이름
"required" : 필수항목 여부(true)
*/
$write_change_fields = array(
	"wr_id" => array("type"=>"int(11) NOT NULL","name"=>"아이디")
	,"wr_num" => array("type"=>"int(11) NOT NULL DEFAULT 0","name"=>"번호")
	,"wr_reply" => array("type"=>"varchar(10) NOT NULL","name"=>"답변")
	,"wr_parent" => array("type"=>"int(11) NOT NULL DEFAULT 0","name"=>"부모아이디")
	,"wr_is_comment" => array("type"=>"tinyint(4) NOT NULL DEFAULT 0","name"=>"댓글여부")
	,"wr_comment" => array("type"=>"int(11) NOT NULL DEFAULT 0","name"=>"댓글")
	,"wr_comment_reply" => array("type"=>"varchar(5) NOT NULL","name"=>"댓글답")
	,"ca_name" => array("type"=>"varchar(255) NOT NULL","name"=>"분류명")
	,"wr_option" => array("type"=>"set('html1','html2','secret','mail') NOT NULL","name"=>"옵션")
	,"wr_subject" => array("type"=>"varchar(255) NOT NULL","name"=>"제목","required"=>true)
	,"wr_content" => array("type"=>"text NOT NULL","name"=>"내용","required"=>true)
	,"wr_seo_title" => array("type"=>"varchar(255) NOT NULL DEFAULT ''","name"=>"SEO제목")
	,"wr_link1" => array("type"=>"text NOT NULL","name"=>"링크1")
	,"wr_link2" => array("type"=>"text NOT NULL","name"=>"링크2")
	,"wr_link1_hit" => array("type"=>"int(11) NOT NULL DEFAULT 0","name"=>"링크1조회")
	,"wr_link2_hit" => array("type"=>"int(11) NOT NULL DEFAULT 0","name"=>"링크2조회")
	,"wr_hit" => array("type"=>"int(11) NOT NULL DEFAULT 0","name"=>"조회")
	,"wr_good" => array("type"=>"int(11) NOT NULL DEFAULT 0","name"=>"추천")
	,"wr_nogood" => array("type"=>"int(11) NOT NULL DEFAULT 0","name"=>"비추천")
	,"mb_id" => array("type"=>"varchar(20) NOT NULL","name"=>"회원ID")
	,"wr_password" => array("type"=>"varchar(255) NOT NULL","name"=>"비번")
	,"wr_name" => array("type"=>"varchar(255) NOT NULL","name"=>"작성자명")
	,"wr_email" => array("type"=>"varchar(255) NOT NULL","name"=>"이메일")
	,"wr_homepage" => array("type"=>"varchar(255) NOT NULL","name"=>"홈페이지")
	,"wr_datetime" => array("type"=>"datetime NOT NULL DEFAULT '0000-00-00 00:00:00'","name"=>"등록일시")
	,"wr_file" => array("type"=>"tinyint(4) NOT NULL DEFAULT 0","name"=>"파일")
	,"wr_last" => array("type"=>"varchar(19) NOT NULL","name"=>"마지막")
	,"wr_ip" => array("type"=>"varchar(255) NOT NULL","name"=>"IP")
	,"wr_facebook_user" => array("type"=>"varchar(255) NOT NULL","name"=>"페이스북ID")
	,"wr_twitter_user" => array("type"=>"varchar(255) NOT NULL","name"=>"트위터ID")
	,"wr_1" => array("type"=>"varchar(255) NOT NULL","name"=>"여분1")
	,"wr_2" => array("type"=>"varchar(255) NOT NULL","name"=>"여분2")
	,"wr_3" => array("type"=>"varchar(255) NOT NULL","name"=>"여분3")
	,"wr_4" => array("type"=>"varchar(255) NOT NULL","name"=>"여분4")
	,"wr_5" => array("type"=>"varchar(255) NOT NULL","name"=>"여분5")
	,"wr_6" => array("type"=>"varchar(255) NOT NULL","name"=>"여분6")
	,"wr_7" => array("type"=>"varchar(255) NOT NULL","name"=>"여분7")
	,"wr_8" => array("type"=>"varchar(255) NOT NULL","name"=>"여분8")
	,"wr_9" => array("type"=>"varchar(255) NOT NULL","name"=>"여분9")
	,"wr_10" => array("type"=>"varchar(255) NOT NULL","name"=>"여분10")
);
//add_replace('get_board_sort_fields', 'u_get_board_sort_fields', 10, 5);//user.03.default.php
//새로운 필드에 맞춰서 수정해 주세요.
$write_change_sort_fields = array(
	array('wr_num, wr_reply', '기본')
	,array('wr_datetime asc', '날짜 이전것 부터')
	,array('wr_datetime desc', '날짜 최근것 부터')
	,array('wr_hit asc, wr_num, wr_reply', '조회수 낮은것 부터')
	,array('wr_hit desc, wr_num, wr_reply', '조회수 높은것 부터')
	,array('wr_last asc', '최근글 이전것 부터')
	,array('wr_last desc', '최근글 최근것 부터')
	,array('wr_comment asc, wr_num, wr_reply', '댓글수 낮은것 부터')
	,array('wr_comment desc, wr_num, wr_reply', '댓글수 높은것 부터')
	,array('wr_good asc, wr_num, wr_reply', '추천수 낮은것 부터')
	,array('wr_good desc, wr_num, wr_reply', '추천수 높은것 부터')
	,array('wr_nogood asc, wr_num, wr_reply', '비추천수 낮은것 부터')
	,array('wr_nogood desc, wr_num, wr_reply', '비추천수 높은것 부터')
	,array('wr_subject asc, wr_num, wr_reply', '제목 오름차순')
	,array('wr_subject desc, wr_num, wr_reply', '제목 내림차순')
	,array('wr_name asc, wr_num, wr_reply', '글쓴이 오름차순')
	,array('wr_name desc, wr_num, wr_reply', '글쓴이 내림차순')
	,array('ca_name asc, wr_num, wr_reply', '분류명 오름차순')
	,array('ca_name desc, wr_num, wr_reply', '분류명 내림차순')
);

/* 게시판 기본구조(아래의 배열 구조를 참조하여 위의 배열변수를 수정해 주세요.)
$write_change_fields = array(
	"wr_id" => array("type"=>"int(11) NOT NULL","name"=>"아이디")
	,"wr_num" => array("type"=>"int(11) NOT NULL DEFAULT 0","name"=>"번호")
	,"wr_reply" => array("type"=>"varchar(10) NOT NULL","name"=>"답변")
	,"wr_parent" => array("type"=>"int(11) NOT NULL DEFAULT 0","name"=>"부모아이디")
	,"wr_is_comment" => array("type"=>"tinyint(4) NOT NULL DEFAULT 0","name"=>"댓글여부")
	,"wr_comment" => array("type"=>"int(11) NOT NULL DEFAULT 0","name"=>"댓글")
	,"wr_comment_reply" => array("type"=>"varchar(5) NOT NULL","name"=>"댓글답")
	,"ca_name" => array("type"=>"varchar(255) NOT NULL","name"=>"분류명")
	,"wr_option" => array("type"=>"set('html1','html2','secret','mail') NOT NULL","name"=>"옵션")
	,"wr_subject" => array("type"=>"varchar(255) NOT NULL","name"=>"제목","required"=>true)
	,"wr_content" => array("type"=>"text NOT NULL","name"=>"내용","required"=>true)
	,"wr_seo_title" => array("type"=>"varchar(255) NOT NULL DEFAULT ''","name"=>"SEO제목")
	,"wr_link1" => array("type"=>"text NOT NULL","name"=>"링크1")
	,"wr_link2" => array("type"=>"text NOT NULL","name"=>"링크2")
	,"wr_link1_hit" => array("type"=>"int(11) NOT NULL DEFAULT 0","name"=>"링크1조회")
	,"wr_link2_hit" => array("type"=>"int(11) NOT NULL DEFAULT 0","name"=>"링크2조회")
	,"wr_hit" => array("type"=>"int(11) NOT NULL DEFAULT 0","name"=>"조회")
	,"wr_good" => array("type"=>"int(11) NOT NULL DEFAULT 0","name"=>"추천")
	,"wr_nogood" => array("type"=>"int(11) NOT NULL DEFAULT 0","name"=>"비추천")
	,"mb_id" => array("type"=>"varchar(20) NOT NULL","name"=>"회원ID")
	,"wr_password" => array("type"=>"varchar(255) NOT NULL","name"=>"비번")
	,"wr_name" => array("type"=>"varchar(255) NOT NULL","name"=>"작성자명")
	,"wr_email" => array("type"=>"varchar(255) NOT NULL","name"=>"이메일")
	,"wr_homepage" => array("type"=>"varchar(255) NOT NULL","name"=>"홈페이지")
	,"wr_datetime" => array("type"=>"datetime NOT NULL DEFAULT '0000-00-00 00:00:00'","name"=>"등록일시")
	,"wr_file" => array("type"=>"tinyint(4) NOT NULL DEFAULT 0","name"=>"파일")
	,"wr_last" => array("type"=>"varchar(19) NOT NULL","name"=>"마지막")
	,"wr_ip" => array("type"=>"varchar(255) NOT NULL","name"=>"IP")
	,"wr_facebook_user" => array("type"=>"varchar(255) NOT NULL","name"=>"페이스북ID")
	,"wr_twitter_user" => array("type"=>"varchar(255) NOT NULL","name"=>"트위터ID")
	,"wr_1" => array("type"=>"varchar(255) NOT NULL","name"=>"여분1")
	,"wr_2" => array("type"=>"varchar(255) NOT NULL","name"=>"여분2")
	,"wr_3" => array("type"=>"varchar(255) NOT NULL","name"=>"여분3")
	,"wr_4" => array("type"=>"varchar(255) NOT NULL","name"=>"여분4")
	,"wr_5" => array("type"=>"varchar(255) NOT NULL","name"=>"여분5")
	,"wr_6" => array("type"=>"varchar(255) NOT NULL","name"=>"여분6")
	,"wr_7" => array("type"=>"varchar(255) NOT NULL","name"=>"여분7")
	,"wr_8" => array("type"=>"varchar(255) NOT NULL","name"=>"여분8")
	,"wr_9" => array("type"=>"varchar(255) NOT NULL","name"=>"여분9")
	,"wr_10" => array("type"=>"varchar(255) NOT NULL","name"=>"여분10")
);
//게시판 기본 정렬을 위한 배열 구조
$write_change_sort_fields = array(
	array('wr_num, wr_reply', '기본')
	,array('wr_datetime asc', '날짜 이전것 부터')
	,array('wr_datetime desc', '날짜 최근것 부터')
	,array('wr_hit asc, wr_num, wr_reply', '조회수 낮은것 부터')
	,array('wr_hit desc, wr_num, wr_reply', '조회수 높은것 부터')
	,array('wr_last asc', '최근글 이전것 부터')
	,array('wr_last desc', '최근글 최근것 부터')
	,array('wr_comment asc, wr_num, wr_reply', '댓글수 낮은것 부터')
	,array('wr_comment desc, wr_num, wr_reply', '댓글수 높은것 부터')
	,array('wr_good asc, wr_num, wr_reply', '추천수 낮은것 부터')
	,array('wr_good desc, wr_num, wr_reply', '추천수 높은것 부터')
	,array('wr_nogood asc, wr_num, wr_reply', '비추천수 낮은것 부터')
	,array('wr_nogood desc, wr_num, wr_reply', '비추천수 높은것 부터')
	,array('wr_subject asc, wr_num, wr_reply', '제목 오름차순')
	,array('wr_subject desc, wr_num, wr_reply', '제목 내림차순')
	,array('wr_name asc, wr_num, wr_reply', '글쓴이 오름차순')
	,array('wr_name desc, wr_num, wr_reply', '글쓴이 내림차순')
	,array('ca_name asc, wr_num, wr_reply', '분류명 오름차순')
	,array('ca_name desc, wr_num, wr_reply', '분류명 내림차순')
);
*/